name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install sphinx sphinx-rtd-theme myst-parser

    - name: Build documentation
      run: |
        # Placeholder for documentation build
        # sphinx-build -b html docs/ docs/_build/html
        echo "Documentation build placeholder - add sphinx documentation later"

    - name: Check README
      run: |
        python -m pip install --upgrade pip
        pip install readme-renderer
        python setup.py check --restructuredtext --strict || true

  validate-examples:
    name: Validate examples in README
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc

    - name: Install fz
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pandas

    - name: Extract and validate Python code from README
      run: |
        # This is a placeholder - could add markdown code block extraction and validation
        echo "README validation placeholder"
        python -c "import fz; print(f'fz version: {fz.__version__}')"
